//
// Created by codewing on 07.11.18.
//

#ifndef SIMPLERENDERENGINEPROJECT_WORMHOLEGAME_H
#define SIMPLERENDERENGINEPROJECT_WORMHOLEGAME_H


class WormholeGame {

};


#endif //SIMPLERENDERENGINEPROJECT_WORMHOLEGAME_H
